In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('global_superstore_2016 (2).xlsx')
pd.set_option('display.max_columns', None)
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2018-11-11,2018-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,Oklahoma,United States,Central US,USCA,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2018-02-05,2018-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,New South Wales,Australia,Oceania,Asia Pacific,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2018-10-17,2018-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,Queensland,Australia,Oceania,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2018-01-28,2018-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,Berlin,Germany,Western Europe,Europe,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2018-11-05,2018-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,Dakar,Senegal,Western Africa,Africa,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [4]:
df.shape

(51290, 24)

In [5]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [6]:
df = df.drop("Postal Code",axis =1)
len(df.columns)

23

In [7]:
df = df.drop(["Row ID","Order ID","Customer ID","Customer Name","Product ID","Product Name","Discount","Profit","Shipping Cost"],axis =1)
len(df.columns)

14

In [8]:
df.columns

Index(['Order Date', 'Ship Date', 'Ship Mode', 'Segment', 'City', 'State',
       'Country', 'Region', 'Market', 'Category', 'Sub-Category', 'Sales',
       'Quantity', 'Order Priority'],
      dtype='object')

In [9]:
df.tail(5)

,Order Date,Ship Date,Ship Mode,Segment,City,State,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority
51285,2019-06-19,2019-06-19,Same Day,Corporate,Kure,Hiroshima,Japan,Eastern Asia,Asia Pacific,Office Supplies,Fasteners,65.10,5,Medium
51286,2018-05-06,2018-05-10,Standard Class,Consumer,Chattanooga,Tennessee,United States,Southern US,USCA,Furniture,Furnishings,16.72,5,High
51287,2016-08-26,2016-08-31,Second Class,Consumer,San Francisco,California,United States,Western US,USCA,Office Supplies,Art,8.56,2,High
51288,2017-02-17,2017-02-21,Standard Class,Home Office,Valinhos,São Paulo,Brazil,South America,LATAM,Office Supplies,Binders,13.44,2,Medium
51289,2017-05-22,2017-05-26,Second Class,Consumer,Tipitapa,Managua,Nicaragua,Central America,LATAM,Office Supplies,Paper,61.38,3,High

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      51290 non-null  datetime64[ns]
 1   Ship Date       51290 non-null  datetime64[ns]
 2   Ship Mode       51290 non-null  object
 3   Segment         51290 non-null  object
 4   City            51290 non-null  object
 5   State           51290 non-null  object
 6   Country         51290 non-null  object
 7   Region          51290 non-null  object
 8   Market          51290 non-null  object
 9   Category        51290 non-null  object
 10  Sub-Category    51290 non-null  object
 11  Sales           51290 non-null  float64
 12  Quantity        51290 non-null  int64
 13  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(1), object(10)
memory usage: 5.5+ MB

In [11]:
df.dtypes

Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Segment                   object
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Category                  object
Sub-Category              object
Sales                    float64
Quantity                   int64
Order Priority            object
dtype: object

In [12]:
print('columns and number of unique values')
dict=[]
for i in df.columns:
    print(f'{i} --> {df[i].nunique()}')

columns and number of unique values
Order Date --> 1430
Ship Date --> 1464
Ship Mode --> 4
Segment --> 3
City --> 3650
State --> 1102
Country --> 165
Region --> 23
Market --> 5
Category --> 3
Sub-Category --> 17
Sales --> 27200
Quantity --> 14
Order Priority --> 4

In [13]:
df = df.drop(["City","State"],axis=1)
df.sample(5)

,Order Date,Ship Date,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority
34159,2019-10-06,2019-10-10,Second Class,Corporate,Germany,Western Europe,Europe,Office Supplies,Binders,28.95,5,High
42460,2019-01-07,2019-01-11,Standard Class,Home Office,United Kingdom,Northern Europe,Europe,Office Supplies,Binders,20.97,3,High
26724,2017-11-21,2017-11-24,Second Class,Consumer,France,Western Europe,Europe,Office Supplies,Fasteners,22.98,2,Critical
16913,2017-12-10,2017-12-12,First Class,Corporate,China,Eastern Asia,Asia Pacific,Office Supplies,Supplies,118.80,9,High
41948,2017-03-09,2017-03-16,Standard Class,Home Office,Iran,Southern Asia,Asia Pacific,Office Supplies,Binders,5.34,1,Low

In [14]:
print('columns and number of unique values')
dict=[]
for i in df.columns:
    print(f'{i} --> {df[i].nunique()}')

columns and number of unique values
Order Date --> 1430
Ship Date --> 1464
Ship Mode --> 4
Segment --> 3
Country --> 165
Region --> 23
Market --> 5
Category --> 3
Sub-Category --> 17
Sales --> 27200
Quantity --> 14
Order Priority --> 4

# ordinal encodin (order wise)
  Ship Mode , 
  Order Priority
  
# Label encodin (normal encodin alpabetical order)
  Segment , 
  Country , 
  Region , 
  market , 
  Category , 
  Sub-Category

In [15]:
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date

In [16]:
df["diff_days"] = df["Ship Date"] - df["Order Date"]
df.diff_days

0       2 days
1       2 days
2       1 days
3       2 days
4       1 days
         ...
51285   0 days
51286   4 days
51287   5 days
51288   4 days
51289   4 days
Name: diff_days, Length: 51290, dtype: timedelta64[ns]

In [17]:
print(max(df["diff_days"]))
print(min(df["diff_days"]))

7 days 00:00:00
0 days 00:00:00

In [18]:
df.columns

Index(['Order Date', 'Ship Date', 'Ship Mode', 'Segment', 'Country', 'Region',
       'Market', 'Category', 'Sub-Category', 'Sales', 'Quantity',
       'Order Priority', 'diff_days'],
      dtype='object')

In [19]:
df = df.drop(["Order Date","Ship Date"],axis=1)
df.columns

Index(['Ship Mode', 'Segment', 'Country', 'Region', 'Market', 'Category',
       'Sub-Category', 'Sales', 'Quantity', 'Order Priority', 'diff_days'],
      dtype='object')

In [20]:
df.head(5)

,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority,diff_days
0,First Class,Consumer,United States,Central US,USCA,Technology,Phones,221.980,2,High,2 days
1,Second Class,Corporate,Australia,Oceania,Asia Pacific,Furniture,Chairs,3709.395,9,Critical,2 days
2,First Class,Consumer,Australia,Oceania,Asia Pacific,Technology,Phones,5175.171,9,Medium,1 days
3,First Class,Home Office,Germany,Western Europe,Europe,Technology,Phones,2892.510,5,Medium,2 days
4,Same Day,Consumer,Senegal,Western Africa,Africa,Technology,Copiers,2832.960,8,Critical,1 days

In [21]:
# df = df.drop(["diff_days"],axis=1)
df.head(5)

,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority,diff_days
0,First Class,Consumer,United States,Central US,USCA,Technology,Phones,221.980,2,High,2 days
1,Second Class,Corporate,Australia,Oceania,Asia Pacific,Furniture,Chairs,3709.395,9,Critical,2 days
2,First Class,Consumer,Australia,Oceania,Asia Pacific,Technology,Phones,5175.171,9,Medium,1 days
3,First Class,Home Office,Germany,Western Europe,Europe,Technology,Phones,2892.510,5,Medium,2 days
4,Same Day,Consumer,Senegal,Western Africa,Africa,Technology,Copiers,2832.960,8,Critical,1 days

In [22]:
train = df
X=train.drop('Sales',axis=1)
y=train['Sales']
print(X.head(5))
print(y.head(5))

      Ship Mode      Segment        Country          Region        Market  \
0   First Class     Consumer  United States      Central US          USCA
1  Second Class    Corporate      Australia         Oceania  Asia Pacific
2   First Class     Consumer      Australia         Oceania  Asia Pacific
3   First Class  Home Office        Germany  Western Europe        Europe
4      Same Day     Consumer        Senegal  Western Africa        Africa

     Category Sub-Category  Quantity Order Priority diff_days
0  Technology       Phones         2           High    2 days
1   Furniture       Chairs         9       Critical    2 days
2  Technology       Phones         9         Medium    1 days
3  Technology       Phones         5         Medium    2 days
4  Technology      Copiers         8       Critical    1 days
0     221.980
1    3709.395
2    5175.171
3    2892.510
4    2832.960
Name: Sales, dtype: float64

In [23]:
# corr_r = train 
# corr_r[corr_r.columns[1:]].corr()['Sales'][:] #corr only on numerical values

In [24]:
df.head(5)

,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority,diff_days
0,First Class,Consumer,United States,Central US,USCA,Technology,Phones,221.980,2,High,2 days
1,Second Class,Corporate,Australia,Oceania,Asia Pacific,Furniture,Chairs,3709.395,9,Critical,2 days
2,First Class,Consumer,Australia,Oceania,Asia Pacific,Technology,Phones,5175.171,9,Medium,1 days
3,First Class,Home Office,Germany,Western Europe,Europe,Technology,Phones,2892.510,5,Medium,2 days
4,Same Day,Consumer,Senegal,Western Africa,Africa,Technology,Copiers,2832.960,8,Critical,1 days

In [25]:
# !pip install AutoViz
# !pip install xlrd

In [26]:
# from autoviz.AutoViz_Class import AutoViz_Class

# #Instantiate the AutoViz class
# AV = AutoViz_Class()

In [27]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

In [28]:
df["Ship Mode"].unique()

array(['First Class', 'Second Class', 'Same Day', 'Standard Class'],
      dtype=object)

In [29]:
df["Ship Mode"] = df["Ship Mode"].map({"Same Day":0,"First Class":1,"Second Class":2,"Standard Class":3})
df.tail(5)

,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority,diff_days
51285,0,Corporate,Japan,Eastern Asia,Asia Pacific,Office Supplies,Fasteners,65.10,5,Medium,0 days
51286,3,Consumer,United States,Southern US,USCA,Furniture,Furnishings,16.72,5,High,4 days
51287,2,Consumer,United States,Western US,USCA,Office Supplies,Art,8.56,2,High,5 days
51288,3,Home Office,Brazil,South America,LATAM,Office Supplies,Binders,13.44,2,Medium,4 days
51289,2,Consumer,Nicaragua,Central America,LATAM,Office Supplies,Paper,61.38,3,High,4 days

In [30]:
df["Order Priority"].unique()

array(['High', 'Critical', 'Medium', 'Low'], dtype=object)

In [31]:
df["Order Priority"] = df["Order Priority"].map({"Critical":0,"High":1,"Medium":2,"Low":3})
df.tail(5)

,Ship Mode,Segment,Country,Region,Market,Category,Sub-Category,Sales,Quantity,Order Priority,diff_days
51285,0,Corporate,Japan,Eastern Asia,Asia Pacific,Office Supplies,Fasteners,65.10,5,2,0 days
51286,3,Consumer,United States,Southern US,USCA,Furniture,Furnishings,16.72,5,1,4 days
51287,2,Consumer,United States,Western US,USCA,Office Supplies,Art,8.56,2,1,5 days
51288,3,Home Office,Brazil,South America,LATAM,Office Supplies,Binders,13.44,2,2,4 days
51289,2,Consumer,Nicaragua,Central America,LATAM,Office Supplies,Paper,61.38,3,1,4 days

In [32]:
print(df["Segment"].unique(),len(df["Segment"].unique()))
print(df["Region"].unique() ,len(df["Region"].unique()))
print(df["Market"].unique() ,len(df["Market"].unique()))
print(df["Category"].unique() ,len(df["Category"].unique()))
print(df["Sub-Category"].unique() ,len(df["Sub-Category"].unique()))
len(df["Country"].unique())

['Consumer' 'Corporate' 'Home Office'] 3
['Central US' 'Oceania' 'Western Europe' 'Western Africa' 'Western US'
 'Southern Asia' 'Western Asia' 'South America' 'Eastern Asia'
 'Southern Europe' 'Eastern Africa' 'Eastern Europe' 'Northern Europe'
 'Central America' 'Eastern US' 'Caribbean' 'Central Africa'
 'Southeastern Asia' 'Southern US' 'North Africa' 'Southern Africa'
 'Canada' 'Central Asia'] 23
['USCA' 'Asia Pacific' 'Europe' 'Africa' 'LATAM'] 5
['Technology' 'Furniture' 'Office Supplies'] 3
['Phones' 'Chairs' 'Copiers' 'Tables' 'Bookcases' 'Art' 'Appliances'
 'Storage' 'Fasteners' 'Machines' 'Accessories' 'Furnishings' 'Binders'
 'Labels' 'Paper' 'Supplies' 'Envelopes'] 17

165

In [33]:
df = df.drop(["Country","diff_days","Order Priority"],axis=1)
df.head()

,Ship Mode,Segment,Region,Market,Category,Sub-Category,Sales,Quantity
0,1,Consumer,Central US,USCA,Technology,Phones,221.980,2
1,2,Corporate,Oceania,Asia Pacific,Furniture,Chairs,3709.395,9
2,1,Consumer,Oceania,Asia Pacific,Technology,Phones,5175.171,9
3,1,Home Office,Western Europe,Europe,Technology,Phones,2892.510,5
4,0,Consumer,Western Africa,Africa,Technology,Copiers,2832.960,8

In [34]:
from sklearn.preprocessing import LabelEncoder
label_object = {}
categorical_columns = ['Sub-Category','Region']
for col in categorical_columns:
    labelencoder = LabelEncoder()
    labelencoder.fit(df[col])
    df[col] = labelencoder.fit_transform(df[col])
    label_object[col] = labelencoder

print(label_object['Region'].inverse_transform(df['Region']))

['Central US' 'Oceania' 'Oceania' ... 'Western US' 'South America'
 'Central America']

In [35]:
df.head()

,Ship Mode,Segment,Region,Market,Category,Sub-Category,Sales,Quantity
0,1,Consumer,5,USCA,Technology,13,221.980,2
1,2,Corporate,12,Asia Pacific,Furniture,5,3709.395,9
2,1,Consumer,12,Asia Pacific,Technology,13,5175.171,9
3,1,Home Office,21,Europe,Technology,13,2892.510,5
4,0,Consumer,19,Africa,Technology,6,2832.960,8

In [36]:
print('Region label encoding values')
print('unique values -->',len(df["Region"].unique()))
print('max value -->' ,df['Region'].max())
print('min value -->' ,df['Region'].min())

print('Sub-Category label encoding values')
print('unique values -->' ,len(df["Sub-Category"].unique()))
print('max value -->' ,df['Sub-Category'].max())
print('min value -->' ,df['Sub-Category'].min())

Region label encoding values
unique values --> 23
max value --> 22
min value --> 0
Sub-Category label encoding values
unique values --> 17
max value --> 16
min value --> 0

# usin map transformin 

### Segment , Market , Category
#### Segment unique values -- 3
#### Market unique values --  5
#### Category unique values -- 3

In [37]:
print(df["Segment"].unique(),len(df["Segment"].unique()))
print(df["Market"].unique() ,len(df["Market"].unique()))
print("USCA --> USA & CANADA \nLATAM --> LATIN AMERICA ")

print(df["Category"].unique() ,len(df["Category"].unique()))

['Consumer' 'Corporate' 'Home Office'] 3
['USCA' 'Asia Pacific' 'Europe' 'Africa' 'LATAM'] 5
USCA --> USA & CANADA
LATAM --> LATIN AMERICA
['Technology' 'Furniture' 'Office Supplies'] 3

In [38]:
# Segment mapping 
df["Segment"] = df["Segment"].map({"Consumer":0,"Corporate":1,"Home Office":2})
# market mapping 
df["Market"] = df["Market"].map({"Africa":0,"Asia Pacific":1,"Europe":2,"LATAM":3,"USCA":4})
# Segment mapping 
df["Category"] = df["Category"].map({"Furniture":0,"Office Supplies":1,"Technology":2})

df.head()

,Ship Mode,Segment,Region,Market,Category,Sub-Category,Sales,Quantity
0,1,0,5,4,2,13,221.980,2
1,2,1,12,1,0,5,3709.395,9
2,1,0,12,1,2,13,5175.171,9
3,1,2,21,2,2,13,2892.510,5
4,0,0,19,0,2,6,2832.960,8

### Ship Mode	
####  Same Day :0 , First Class :1 , Second Class :2 , Standard Class:3


### Segment
#### Consumer :0 , Corporate :1, Home Office :2


### Market
#### Africa :0 , Asia Pacific :1 , Europe :2 , LATAM :3 , USCA :4 


### Category
#### Furniture :0 , Office Supplies :1 , Technology :2\

In [39]:
train = df

In [40]:
corr_r = train 
corr_r[corr_r.columns[1:]].corr()['Sales'][:] #corr only on numerical values

Segment         0.001847
Region          0.016452
Market         -0.018329
Category        0.036172
Sub-Category    0.017381
Sales           1.000000
Quantity        0.313577
Name: Sales, dtype: float64

In [41]:
X = df.drop('Sales',axis=1)
y = df['Sales']
print(X.shape)
print(y.shape)

(51290, 7)
(51290,)

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [43]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [44]:
print(X_train[0:2])
print(X_test[0:2])
X_vald = X_train
y_vald = y_train
print(y_train[0:2])
print(y_test[0:2])

[[1.         1.         0.63636364 0.25       0.         1.
  0.30769231]
 [1.         0.5        0.5        0.5        0.5        0.125
  0.23076923]]
[[1.         0.         0.13636364 0.75       0.5        0.125
  0.07692308]
 [0.33333333 0.         0.63636364 0.25       0.5        0.4375
  0.        ]]
2558     2276.4825
15041     116.0400
Name: Sales, dtype: float64
49728    21.5520
45547     4.5156
Name: Sales, dtype: float64

In [45]:
from sklearn.ensemble import RandomForestRegressor
model1=RandomForestRegressor()
model1.fit(X_train,y_train)
model1.score(X_vald,y_vald)

0.7576438803427121

In [46]:
from sklearn.ensemble import ExtraTreesRegressor
model2=ExtraTreesRegressor()
model2.fit(X_train,y_train)
model2.score(X_vald,y_vald)

0.8047531075568866

In [47]:
# n_estimators = [int(x) for x in np.linspace(start = 200, stop = 1000, num = 5)]
# max_features = ['auto', 'sqrt']
# max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
# max_depth.append(None)
# min_samples_split = [2, 5, 10]
# min_samples_leaf = [1, 2, 4]
# bootstrap = [True, False]
# random_grid = {'n_estimators': n_estimators,
#                'max_features': max_features,
#                'max_depth': max_depth,
#                'min_samples_split': min_samples_split,
#                'min_samples_leaf': min_samples_leaf,
#                'bootstrap': bootstrap}

In [50]:
import pickle
with open('sales_pred.pkl','wb') as f:
    pickle.dump(model2,f)

In [51]:
with open('sales_pred.pkl','rb') as f:
    forest= pickle.load(f)

In [48]:
# sns.distplot(y_test-y_pred)
# plt.show()

In [49]:
# plt.scatter(y_test, y_pred, alpha = 0.5)
# plt.xlabel("y_test")
# plt.ylabel("y_pred")
# plt.show()